# Generated by Django 2.2.10 on 2020-02-09 08:53

import common.baseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200208_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacture_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('stock_code', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
            ],
            bases=(models.Model, common.baseModel.BaseModel),
        ),
    ]
