# Generated by Django 3.0.3 on 2020-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_category_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
