version: '3'

services:
  db:
    build: ./docker/db/
    ports:
      - "30307:3306"
    volumes:
      - db_data:/var/lib/mysq
    environment:
      POSTGRES_PASSWORD: root
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "4201:4200"
      - "90:80"
    depends_on:
      - db
  # wsgi:
  #   build: ./docker/wsgi
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "90:80"
  #   depends_on:
  #     - db
volumes:
  db_data: