# Generated by Django 3.0.3 on 2020-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201030_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
