# Generated by Django 3.0.3 on 2020-04-05 13:23

import common.baseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=200)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
            ],
            bases=(models.Model, common.baseModel.BaseModel),
        ),
        migrations.CreateModel(
            name='authToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('expire_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.user')),
            ],
            bases=(models.Model, common.baseModel.BaseModel),
        ),
    ]
